apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: nextend-broker
build:
  artifacts:
    - image: nextend/broker
      jib:
        project: nl.nextend:nextend-broker
manifests:
  rawYaml:
    - k8s/k8s-broker-prod.yaml
portForward:
  - resourceType: service
    resourceName: broker-np
    namespace: default
    port: 6933
    localPort: 6933